import * as vscode from 'vscode';
import { loadSpec, SpecError } from '../parser/loadSpec';
import { buildHttpProject } from '../generator/httpProject/build';
import { fetchText, FetchError } from '../utils/fetchText';
import { fileExists, directoryHasEntries, joinPath } from '../utils/fsHelpers';
import { writeProject, WriteSummary, MANIFEST_RELATIVE_PATH } from '../utils/projectWriter';

const SPEC_FILE_FILTERS = { 'OpenAPI/Swagger spec': ['json', 'yaml', 'yml'] };

async function pickWorkspaceFolder(): Promise<vscode.WorkspaceFolder | undefined> {
  const folders = vscode.workspace.workspaceFolders;
  if (!folders || folders.length === 0) {
    vscode.window.showErrorMessage('PlaySpec: open a folder or workspace first — generated tests are written into it.');
    return undefined;
  }
  if (folders.length === 1) return folders[0];
  return vscode.window.showWorkspaceFolderPick({ placeHolder: 'Select the workspace folder to generate tests into' });
}

async function readSpecFromFileUri(uri: vscode.Uri): Promise<string> {
  const bytes = await vscode.workspace.fs.readFile(uri);
  return Buffer.from(bytes).toString('utf8');
}

async function resolveOutputFolder(workspaceFolder: vscode.WorkspaceFolder): Promise<vscode.Uri | undefined> {
  const configuredName = vscode.workspace.getConfiguration('playspec').get<string>('outputFolderName', 'playwright-tests');
  const outputUri = vscode.Uri.joinPath(workspaceFolder.uri, configuredName);

  // A PlaySpec manifest here means this folder was already generated by us —
  // regeneration is designed to be safe against that (see projectWriter.ts),
  // so no need to interrupt with a confirmation. Only warn if the folder
  // exists with unrelated content we'd otherwise be writing into blind.
  const looksLikeExistingPlaySpecProject = await fileExists(joinPath(outputUri, MANIFEST_RELATIVE_PATH));
  if (!looksLikeExistingPlaySpecProject && (await directoryHasEntries(outputUri))) {
    const choice = await vscode.window.showWarningMessage(
      `"${configuredName}" already exists in ${workspaceFolder.name} and doesn't look like a PlaySpec project (no tests/spec/.playspec-manifest.json found). Generating here may mix PlaySpec's files in with what's already there.`,
      { modal: true },
      'Continue',
      'Cancel'
    );
    if (choice !== 'Continue') return undefined;
  }

  return outputUri;
}

interface GenerationResult {
  outputUri: vscode.Uri;
  summary: WriteSummary;
}

function formatFileList(files: string[], max = 5): string {
  if (files.length <= max) return files.join(', ');
  return `${files.slice(0, max).join(', ')}, +${files.length - max} more`;
}

async function runGeneration(specText: string, sourceLabel: string): Promise<void> {
  const workspaceFolder = await pickWorkspaceFolder();
  if (!workspaceFolder) return;

  // Only the parse/build/write work runs inside withProgress — its spinner
  // stays on screen until this whole callback resolves, so anything that
  // waits on user interaction (like the completion message's buttons below)
  // must happen *after* this returns, or the progress notification would
  // sit there indefinitely looking hung while it's actually just waiting
  // on a toast the user has no reason to expect yet.
  const result = await vscode.window.withProgress(
    { location: vscode.ProgressLocation.Notification, title: 'PlaySpec: generating Playwright tests', cancellable: false },
    async (progress): Promise<GenerationResult | undefined> => {
      progress.report({ message: `Parsing ${sourceLabel}...` });

      let api: any;
      try {
        ({ api } = await loadSpec(specText));
      } catch (err) {
        if (err instanceof SpecError) {
          vscode.window.showErrorMessage(`PlaySpec: ${err.message}`);
          return undefined;
        }
        throw err;
      }

      progress.report({ message: 'Resolving output folder...' });
      const outputUri = await resolveOutputFolder(workspaceFolder);
      if (!outputUri) return undefined;

      const skipResponseValidation = vscode.workspace.getConfiguration('playspec').get<boolean>('skipResponseValidation', false);

      progress.report({ message: 'Generating test files...' });
      let built;
      try {
        built = buildHttpProject(api, { skipResponseValidation });
      } catch (err: any) {
        vscode.window.showErrorMessage(`PlaySpec: failed to generate tests from this spec: ${err.message || err}`);
        return undefined;
      }

      if (built.operationCount === 0) {
        vscode.window.showWarningMessage('PlaySpec: no operations were found in this spec — nothing to generate.');
        return undefined;
      }

      progress.report({ message: 'Writing files...' });
      const summary = await writeProject(outputUri, built);

      return { outputUri, summary };
    }
  );

  if (!result) return;

  const { outputUri, summary } = result;
  const showFolderPrefix = (vscode.workspace.workspaceFolders?.length ?? 0) > 1;
  const relativeFolder = vscode.workspace.asRelativePath(outputUri, showFolderPrefix);

  const testParts: string[] = [];
  if (summary.operationsCreated.length) testParts.push(`${summary.operationsCreated.length} new`);
  if (summary.operationsUpdated.length) testParts.push(`${summary.operationsUpdated.length} updated`);
  if (summary.operationsUnchanged) testParts.push(`${summary.operationsUnchanged} unchanged`);
  const testsSummary = testParts.length ? testParts.join(', ') + ' test file(s)' : 'no test files';

  const openReadme = 'Open README';
  const reveal = 'Reveal in Explorer';
  const choice = await vscode.window.showInformationMessage(
    `PlaySpec: ${testsSummary} in ${relativeFolder}.`,
    openReadme,
    reveal
  );

  if (choice === openReadme) {
    const readmeUri = vscode.Uri.joinPath(outputUri, 'README.md');
    const doc = await vscode.workspace.openTextDocument(readmeUri);
    await vscode.window.showTextDocument(doc, { preview: false });
  } else if (choice === reveal) {
    await vscode.commands.executeCommand('revealInExplorer', outputUri);
  }

  const warnings: string[] = [];
  if (summary.operationsOrphaned.length) {
    warnings.push(
      `${summary.operationsOrphaned.length} test file(s) no longer match any operation in the spec (left in place, not deleted): ${formatFileList(summary.operationsOrphaned)}.`
    );
  }
  if (summary.paramsUnparseable) {
    warnings.push(`tests/data/params.ts couldn't be parsed automatically (likely hand-edited beyond its usual format) — new/changed param entries were not merged in; check it manually.`);
  }
  if (summary.paramsDroppedKeys.length) {
    warnings.push(
      `tests/data/params.ts: removed ${summary.paramsDroppedKeys.length} entr${summary.paramsDroppedKeys.length === 1 ? 'y' : 'ies'} for operation(s) no longer in the spec: ${formatFileList(summary.paramsDroppedKeys)}.`
    );
  }
  if (warnings.length) {
    vscode.window.showWarningMessage(`PlaySpec: ${warnings.join(' ')}`);
  }
}

export async function generateFromFileCommand(): Promise<void> {
  const workspaceFolder = vscode.workspace.workspaceFolders?.[0];
  const uris = await vscode.window.showOpenDialog({
    canSelectMany: false,
    openLabel: 'Generate Tests from This Spec',
    filters: SPEC_FILE_FILTERS,
    defaultUri: workspaceFolder?.uri,
  });
  if (!uris || uris.length === 0) return;

  const specText = await readSpecFromFileUri(uris[0]);
  await runGeneration(specText, vscode.workspace.asRelativePath(uris[0]));
}

export async function generateFromExplorerCommand(resource?: vscode.Uri): Promise<void> {
  if (!resource) {
    await generateFromFileCommand();
    return;
  }
  const specText = await readSpecFromFileUri(resource);
  await runGeneration(specText, vscode.workspace.asRelativePath(resource));
}

export async function generateFromUrlCommand(): Promise<void> {
  const url = await vscode.window.showInputBox({
    prompt: 'URL of the OpenAPI/Swagger spec (JSON or YAML)',
    placeHolder: 'https://api.example.com/openapi.json',
    validateInput: (value) => {
      if (!value.trim()) return 'Enter a URL.';
      try {
        const parsed = new URL(value.trim());
        if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') return 'URL must start with http:// or https://';
      } catch {
        return 'Not a valid URL.';
      }
      return undefined;
    },
  });
  if (!url) return;

  let specText: string;
  try {
    specText = await vscode.window.withProgress(
      { location: vscode.ProgressLocation.Notification, title: `PlaySpec: fetching ${url}...` },
      () => fetchText(url.trim())
    );
  } catch (err) {
    if (err instanceof FetchError) {
      vscode.window.showErrorMessage(`PlaySpec: ${err.message}`);
      return;
    }
    throw err;
  }

  await runGeneration(specText, url);
}
