import * as http from 'http';
import * as fs from 'fs';
import * as path from 'path';
import * as url from 'url';

// Playwright's HTML report needs to be *served*, not opened as a file:// URL
// — its trace-viewer links fetch trace .zip data via fetch(), which fails
// under file://. This is a minimal, dependency-free static server for a
// single report folder, reused across opens (keyed by folder path) so
// re-opening the same project's report doesn't spawn a new server each time.
// Files are read fresh from disk per-request (no caching), so it keeps
// serving current content after the report folder is regenerated by a
// later test run without needing a restart.

const MIME_TYPES: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.zip': 'application/zip',
  '.webm': 'video/webm',
  '.mp4': 'video/mp4',
  '.txt': 'text/plain; charset=utf-8',
};

function contentTypeFor(filePath: string): string {
  return MIME_TYPES[path.extname(filePath).toLowerCase()] || 'application/octet-stream';
}

interface ServerEntry {
  server: http.Server;
  port: number;
}

const servers = new Map<string, ServerEntry>();

function startServer(rootDir: string): Promise<ServerEntry> {
  return new Promise((resolve, reject) => {
    const server = http.createServer((req, res) => {
      const parsed = url.parse(req.url || '/');
      let pathname = decodeURIComponent(parsed.pathname || '/');
      if (pathname === '/') pathname = '/index.html';

      const resolved = path.normalize(path.join(rootDir, pathname));
      // Guard against a path escaping rootDir via "..".
      if (resolved !== rootDir && !resolved.startsWith(rootDir + path.sep)) {
        res.writeHead(403);
        res.end('Forbidden');
        return;
      }

      fs.readFile(resolved, (err, data) => {
        if (err) {
          res.writeHead(404);
          res.end('Not found');
          return;
        }
        res.writeHead(200, { 'Content-Type': contentTypeFor(resolved) });
        res.end(data);
      });
    });

    server.once('error', reject);
    // 127.0.0.1 only — same locally-reachable-while-running exposure as
    // `npx playwright show-report` itself already has, nothing new.
    server.listen(0, '127.0.0.1', () => {
      const address = server.address();
      const port = typeof address === 'object' && address ? address.port : 0;
      server.removeListener('error', reject);
      resolve({ server, port });
    });
  });
}

/** Starts (or reuses) a static server for `reportDirFsPath` and returns its port. */
export async function getReportServerPort(reportDirFsPath: string): Promise<number> {
  const key = path.normalize(reportDirFsPath);
  const existing = servers.get(key);
  if (existing && existing.server.listening) return existing.port;

  const entry = await startServer(key);
  servers.set(key, entry);
  return entry.port;
}

/** Closes every report server this extension has started — call from deactivate(). */
export function disposeReportServers(): void {
  for (const { server } of servers.values()) {
    server.close();
  }
  servers.clear();
}
