import { jsString } from '../naming';
import { SecurityScheme } from '../security';

export function packageJson(projectName: string, tagSlugs: string[] = []): string {
  const scripts: Record<string, string> = {
    test: 'playwright test',
    report: 'playwright show-report',
  };
  // One independent script per tag, so a single tag's tests can be run in
  // isolation without invoking the whole suite. Each tag is a directory of
  // one-file-per-operation spec files (see README's "Test files" section).
  for (const slug of tagSlugs) {
    scripts[`test:${slug}`] = `playwright test tests/spec/${slug}/`;
  }

  return JSON.stringify(
    {
      name: projectName,
      version: '1.0.0',
      description: `Playwright API tests generated by PlaySpec from an OpenAPI spec.`,
      scripts,
      devDependencies: {
        '@playwright/test': '^1.46.1',
        '@types/node': '^22.4.0',
      },
      dependencies: {
        dotenv: '^16.4.5',
      },
    },
    null,
    2
  );
}

export function playwrightConfig(baseUrl: string): string {
  return `import { defineConfig } from '@playwright/test';
import 'dotenv/config';

/**
 * Pure API-testing config: no browser projects are needed since every test
 * uses Playwright's \`request\` fixture directly against the HTTP API.
 * See https://playwright.dev/docs/api-testing
 */
export default defineConfig({
  testDir: './tests/spec',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    // Always exactly one trailing slash, whether this came from BASE_URL or
    // the default below — request paths in tests/spec are relative (no
    // leading "/", see helpers/url.ts and build.ts's urlExprFor), and
    // resolving a relative path against a baseURL *without* a trailing
    // slash drops baseURL's last path segment entirely (e.g. "/api/v1"
    // vanishing, "GET /users" silently becoming a request to
    // "/users" instead of "/api/v1/users"). This has to be normalized here,
    // at runtime — a BASE_URL override in your own .env could just as
    // easily be missing the trailing slash as the generated default.
    baseURL: (process.env.BASE_URL || ${jsString(baseUrl)}).replace(/\\/*$/, '/'),
    extraHTTPHeaders: {
      Accept: 'application/json',
    },
    trace: 'on-first-retry',
  },
});
`;
}

export function envSample({
  authSchemes,
  baseUrl,
  skipResponseValidation,
}: {
  authSchemes: { scheme: SecurityScheme; envPrefix: string }[];
  baseUrl: string;
  skipResponseValidation: boolean;
}): string {
  const lines = [
    `# Base URL of the API under test (overrides the spec's "servers" entry).`,
    `BASE_URL=${baseUrl}`,
    '',
    '# Set to "true" to skip response-body shape validation entirely (tests still',
    '# assert the HTTP status code). Useful while your test data in tests/data/params.ts',
    "# doesn't yet line up with what your environment actually returns.",
    `SKIP_RESPONSE_VALIDATION=${skipResponseValidation ? 'true' : 'false'}`,
    '',
  ];
  for (const { scheme, envPrefix } of authSchemes) {
    if (scheme.type === 'http-bearer') {
      lines.push(
        `# Bearer token for the "${scheme.name}" security scheme, sent as: Authorization: Bearer <token>`,
        `${envPrefix}_BEARER_TOKEN=`,
        ''
      );
    } else if (scheme.type === 'http-basic') {
      lines.push(
        `# HTTP Basic credentials for the "${scheme.name}" security scheme, sent as: Authorization: Basic base64(user:pass)`,
        `${envPrefix}_USERNAME=`,
        `${envPrefix}_PASSWORD=`,
        ''
      );
    } else if (scheme.type === 'apiKey') {
      lines.push(
        `# API key for the "${scheme.name}" security scheme, sent in header "${scheme.headerName || scheme.name}"`,
        `${envPrefix}_API_KEY=`,
        ''
      );
    }
  }
  return lines.join('\n');
}

// One file per declared security scheme, keyed by the scheme's own name from the
// spec — never merged into a single shared header-builder. That's what keeps
// filling in credentials for one scheme from ever affecting another: each test
// only calls the specific scheme function(s) its own operation requires.
export function bearerAuthFile(scheme: SecurityScheme, envPrefix: string, functionName: string): string {
  return `import 'dotenv/config';

/** Bearer token for the "${scheme.name}" security scheme (see .env.sample). */
export function ${functionName}(): Record<string, string> {
  const token = process.env.${envPrefix}_BEARER_TOKEN;
  return token ? { Authorization: \`Bearer \${token}\` } : {};
}
`;
}

export function basicAuthFile(scheme: SecurityScheme, envPrefix: string, functionName: string): string {
  return `import 'dotenv/config';

/** HTTP Basic credentials for the "${scheme.name}" security scheme (see .env.sample). */
export function ${functionName}(): Record<string, string> {
  const username = process.env.${envPrefix}_USERNAME;
  const password = process.env.${envPrefix}_PASSWORD;
  if (!username || !password) return {};
  const encoded = Buffer.from(\`\${username}:\${password}\`).toString('base64');
  return { Authorization: \`Basic \${encoded}\` };
}
`;
}

export function apiKeyAuthFile(scheme: SecurityScheme, envPrefix: string, functionName: string): string {
  const headerName = scheme.headerName || scheme.name;
  return `import 'dotenv/config';

/** API key for the "${scheme.name}" security scheme (see .env.sample). */
export function ${functionName}(): Record<string, string> {
  const key = process.env.${envPrefix}_API_KEY;
  return key ? { ${jsString(headerName)}: key } : {};
}
`;
}

export function urlHelperFile(): string {
  return `import { testParams } from '../data/params';

/**
 * Builds a concrete URL from a path template, substituting \`{name}\` path
 * parameters and appending query parameters using the values in
 * tests/data/params.ts. Throws a clear error if that file is missing an
 * entry/value a path param needs, rather than silently sending a broken
 * request. A query param whose value is missing or blank ("") is left out
 * of the request entirely — that's the default for an optional query param
 * with no explicit example in the spec; fill in a value in params.ts to
 * have it sent.
 *
 * Strips any leading "/" from pathTemplate: request paths must be relative
 * to playwright.config.ts's (trailing-slash) baseURL, or standard
 * URL-resolution rules drop baseURL's own path entirely (see
 * playwright.config.ts's comment on baseURL for the full explanation).
 */
export function buildUrl(operationKey: string, pathTemplate: string, queryParamNames: string[] = []): string {
  const values = testParams[operationKey];
  if (!values) {
    throw new Error(\`No entry for "\${operationKey}" in tests/data/params.ts\`);
  }

  let url = pathTemplate.replace(/^\\/+/, '');
  for (const match of pathTemplate.matchAll(/\\{([^}]+)\\}/g)) {
    const name = match[1];
    if (!values[name]) {
      throw new Error(\`Missing value for "\${name}" in tests/data/params.ts under "\${operationKey}"\`);
    }
    url = url.replace(\`{\${name}}\`, encodeURIComponent(values[name]));
  }

  const query = queryParamNames
    .filter((name) => values[name])
    .map((name) => \`\${encodeURIComponent(name)}=\${encodeURIComponent(values[name])}\`)
    .join('&');

  return query ? \`\${url}?\${query}\` : url;
}
`;
}

export function assertSchemaHelper(): string {
  return `import { expect } from '@playwright/test';

/**
 * Asserts that every top-level key present in \`expectedShape\` also exists on
 * \`actual\`. This is intentionally a subset check (not exact-shape / not deep
 * value equality) so tests stay robust to APIs that return extra fields or
 * live data that differs from the spec's static example.
 */
export function expectShapeMatches(actual: unknown, expectedShape: Record<string, unknown> | null | undefined) {
  if (!expectedShape || typeof expectedShape !== 'object') return;
  if (!actual || typeof actual !== 'object') {
    throw new Error('Expected a JSON object response body to compare against the spec example, got: ' + JSON.stringify(actual));
  }
  for (const key of Object.keys(expectedShape)) {
    expect(actual, \`response body missing key "\${key}" documented in the OpenAPI spec\`).toHaveProperty(key);
  }
}

/**
 * Like \`expectShapeMatches\`, but also handles responses whose spec is a top-level
 * array schema (\`schema: { type: array, items: {...} } \`, no top-level \`example\`) —
 * asserts the body is an array and, if it's non-empty, checks the first item's
 * shape against the item example/schema.
 */
export function expectResponseMatches(actual: unknown, expected: unknown) {
  if (expected === null || expected === undefined) return;
  if (Array.isArray(expected)) {
    expect(Array.isArray(actual), 'expected response body to be an array').toBe(true);
    const actualArray = actual as unknown[];
    const itemExample = expected[0];
    if (actualArray.length > 0 && itemExample && typeof itemExample === 'object' && !Array.isArray(itemExample)) {
      expectShapeMatches(actualArray[0], itemExample as Record<string, unknown>);
    }
    return;
  }
  if (typeof expected === 'object') {
    expectShapeMatches(actual, expected as Record<string, unknown>);
  }
}
`;
}

export function readme(projectName: string, opCount: number, tagSlugs: string[] = []): string {
  const perTagScripts = tagSlugs.length
    ? `\nEach tag also gets its own independent script, so you can run just one spec file:\n\n\`\`\`bash\n${tagSlugs
        .map((slug) => `npm run test:${slug}`)
        .join('\n')}\n\`\`\`\n`
    : '';

  return `# ${projectName}

Playwright API tests generated from an OpenAPI/Swagger spec by the PlaySpec VS Code extension.
${opCount} operation(s) were found in the spec and turned into smoke tests under \`tests/spec/<tag>/\`,
one file per operation.

Each test calls the endpoint directly over HTTP (via Playwright's \`request\` fixture — no browser
involved), asserts the response status is one of the spec's documented success codes, and — where
the spec provides a JSON example or schema — checks the response body contains the expected keys.

## Setup

\`\`\`bash
npm install
npx playwright install
cp .env.sample .env   # fill in credentials / base URL
\`\`\`

## Run

\`\`\`bash
npm test
npm run report
\`\`\`
${perTagScripts}

## Test data

Path parameters (e.g. the \`{id}\` in \`/api/user/{id}\`) and every query parameter an operation
declares — required or optional — live in \`tests/data/params.ts\`, keyed by \`"METHOD /path"\`.
Path params and required query params are pre-filled with placeholders derived from the spec's
\`example\`/\`default\`/\`enum\` values (or a type-based guess if the spec doesn't declare one), since
a real ID often doesn't exist anywhere in the spec itself — edit those with real values for your
environment. Optional query params are listed too, but left **blank** unless the spec declared an
explicit example — a blank value means that param is left out of the request entirely; fill one in
to have it sent. Every test that needs one reads from this file at runtime (via
\`tests/helpers/url.ts\`) instead of a value baked into the test file.

Request bodies are still generated inline per test from the spec's schema — edit the test file
directly if a specific body needs different data.

Set \`SKIP_RESPONSE_VALIDATION=true\` in \`.env\` to skip response-body shape checks entirely (the
HTTP status code is still asserted) — useful before you've filled in \`tests/data/params.ts\` with
values that actually resolve to something in your environment.

## Test files

Each operation gets its own file, \`tests/spec/<tag>/<method>-<path>.spec.ts\` — e.g.
\`tests/spec/pets/get-pets-id.spec.ts\`. Edit these freely: add assertions, change the request, whatever
you need. \`tests/spec/.playspec-manifest.json\` is bookkeeping PlaySpec uses to know, next time you
regenerate, whether a given operation's file would come out any different — **commit it to version
control** alongside the tests so regeneration stays safe for everyone working on this project.

## Notes & limitations

- Only \`application/json\` request/response bodies are handled.
- Each test only sends the credentials for the security scheme(s) that specific operation
  declares in the spec (see \`tests/helpers/auth/*.ts\`, one file per named scheme) - filling in
  credentials for an unrelated scheme in \`.env\` never affects other tests.
- When an operation lists multiple alternative \`security\` requirements (i.e. "either auth method
  works"), only the first alternative is used.
- Cookie-based parameters and OAuth2 flows are not generated; add them manually if your API needs them.

## Regenerating

Re-run **PlaySpec: Generate Playwright Tests from Spec File...** (or **...from Spec URL...**) against
an updated spec to refresh this project. This is designed to be safe to do repeatedly:

- An operation's test file is only rewritten if that operation actually changed in the spec (compared
  via a content hash in \`tests/spec/.playspec-manifest.json\`) — an unrelated hand-edited test is
  never touched.
- \`tests/data/params.ts\` is merged, not replaced — values you've already filled in are kept; only
  genuinely new parameters get placeholder entries added.
- \`package.json\` only ever gets scripts/dependencies *added*, never removed or overwritten, if you've
  hand-added your own.
- \`playwright.config.ts\`, \`.env.sample\`, \`README.md\`, and the \`tests/helpers/\` files are only
  created the first time — never touched again, so your customizations to them are safe.
- If an operation is removed from the spec, its test file is left in place (not deleted) — PlaySpec
  will tell you which file(s) no longer match anything, so you can remove them yourself if you want to.
`;
}
